networks:
  default:
    external:
      name: aimaplus_default
      
services:
  assistant-bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main_bot.py
    env_file:
      - .env.docker
    volumes:
      - .:/app
      
  assistant-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main_api.py
    ports:
      - "8090:8000"
    env_file:
      - .env.docker
    volumes:
      - .:/app