networks:
  default:
    external:
      name: aimaplus_default
      
services:
  assistant-review:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main_review.py
    env_file:
      - .env.docker
    volumes:
      - .:/app